### ISSUE TITLE
[Bug] Invalid character on first line of note in Safari

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#199]
**Describe the bug**
When you make a new note in Safari, a red dot appears. Inspecting the code, it says there's an invalid character. This issue does not happen in Firefox or Chrome.,

**To Reproduce**
Make a new note.

**Screenshots**

<img width="195" alt="Screen Shot 2019-12-31 at 1 02 26 PM" src="https://user-images.githubusercontent.com/11951801/71631398-18598a00-2bce-11ea-952c-3a00d367bc64.png">
<img width="582" alt="Screen Shot 2019-12-31 at 1 03 45 PM" src="https://user-images.githubusercontent.com/11951801/71631399-18598a00-2bce-11ea-8205-117745ae86e4.png">

**Comment by kcvgan** [comment]
Is this still up for grabs?
I'm having trouble reproducing it, perhaps it was fixed?

**Comment by taniarascia** [comment]
Okay, new information: it only happens when you create a new note with the control + alt + n command, not by clicking the button. And yes, @kcvgan, it's still up for grabs and an issue. Hopefully that helps.

**Comment by taniarascia** [comment]
Ah yeah, I can reproduce the error on Chrome as well, by typing alt + n, then alt + control + n, which gives the red dot instead of opening a new note. Maybe CodeMirror has some way of handling this properly...

**Comment by kcvgan** [comment]
Well I found a workaround somehow. I don't know if it's the right way as it seems a bit hacky.
First things first, from the [CodeMirror docs](https://codemirror.net/doc/manual.html#config):
<img width="616" alt="image" src="https://user-images.githubusercontent.com/13578888/73123727-48a90400-3f93-11ea-8aa9-6fbfa972f60b.png">

This is where the red dot comes from. I don't know however, if overloading the method to catch a specific character and replace it with an empty char would be too good. 
Even then, I was unable to overload the method, could be due to typings of the EditorOptions. Bumping the typings and CodeMirror to their latest versions did not help.

In NoteEditor.tsx where the editor is rendered:
```typescript
...
          <CodeMirror
            className="editor mousetrap"
            value={activeNote.text}
            options={codeMirrorOptions}
            editorDidMount={editor => {
              editor.focus()
              editor.setCursor(0)
            }}
...
```
the editor.focus() seems to focus the editor instantly and somehow the character (created by the shortcut) is inserted.
What I tried was:
```typescript
...
            editorDidMount={editor => {
              setTimeout(() => {
                editor.focus()
              }, 0)
              editor.setCursor(0)
            }}
...
```
The timeout makes the transition and focus still instantaneous (or at least from the user's perspective) and it skips over the character and solves the problem.

Let me know whether this would be sufficient or too hacky.
While I'm not entirely comfortable with this solution, it's simple and _just works_.

**Comment by taniarascia** [comment]
If it's simple, and just works, sounds great! If we discover an issue with it later, we can always revisit it. 🙂 Thanks for looking into this.

**Comment by taniarascia** [comment]
Closed in #208.

**Comment by taniarascia** [comment]
I'm still getting this issue. 😞

**Comment by kcvgan** [comment]
I'm sorry, I'll try looking for a better solution. 
I've just tried to replicate it and CTRL + ALT + N on new note seems to be working. Pressing it again however, produces the bug.

I took a different approach this time.
In the useKey hook I added this:

```typescript
...
useEffect(() => {
    mousetrap.bindGlobal(key, (event: Event) => {
      event.preventDefault()
      if (actionRef.current) {
        actionRef.current()
      }
    })
...
```
Turns out the event can be accessed and preventing the default behavior (which is inserting the ASCII code for shift out - 14) is stopped and the desired function is called.
I don't know if this is fine since it also touches every other key combination out there. They seem to be working fine still. All this does is preventDefault and leaves the `actionRef.current()` call intact.

**Comment by taniarascia** [comment]
It's worth a shot!

**Comment by taniarascia** [comment]
Definitely getting better...Safari and Firefox seem to be working completely, even for `alt` + `n`, having the `n` in the "pending" state, then `alt` + `control` + `n` to make a new note. Chrome is the one that still has the red dot in that state. However, I think that's pretty rare compared to the issue of Safari having it always, so I can live with that for now. 🙂 Thanks again for looking into this.
