### ISSUE TITLE
[Bug] signup / signin not working

### ISSUE THREAD

**Issue by betodasilva** [taniarascia/takenote#240]
**Describe the bug**
I've tried the app a while ago and pretended to sync with my github account today.
Back on homepage I see signup/signin buttons but when I click both of them, the error are returned as parameters in the url:
error=invalid_request&error_description=no%20connections%20enabled%20for%20the%20client&state=UDdMLlJacnFEMEh%2BalpWbFdSa2NlVG5pVnliQncuR0d4UGlPN25QOW5ERA%3D%3D

parsed description below:
no connections enable for the client

**To Reproduce**
1. Click 'Try it out'. Write something
2. Go back to home page
3. Click on signup or signin button.

**Expected behavior**
See a signup form or github authentication.

**Comment by taniarascia** [comment]
This is a caching issue...its redirecting to the wrong domain. I’ll have to figure out how to invalidate the cache.

**Comment by taniarascia** [comment]
For now, if you clear your browser’s cache or use a different browser, it will work.

**Comment by betodasilva** [comment]
Thanks for the quick reply.

I cleared the cache
Now I can try the app again. My notes are being saved on localstorage normally.

But I see that there's no signup/signin for now (and consequently no sync with github), right?
https://github.com/taniarascia/takenote/blob/master/src/client/containers/LandingPage.tsx

Are you planning to implement it?

**Comment by betodasilva** [comment]
I would love to contribute to this but not sure if I can do it. In the meanwhile I'll try to help with other beginner-friendly issues. Thanks for the time you dedicated to this app and all your tutorials. Big fan.

**Comment by taniarascia** [comment]
Great! I'm going to leave this issue here for anyone else that encounters it. It'll probably affect a few more people who had the old one set up. And yes, GitHub will still be implemented, but I had to totally re-do some of the architecture and move servers to be able to properly authenticate going forward. I'm glad all your notes were persisted between servers, that's a relief. (However, they will be lost when GitHub is finally integrated completely).
