### ISSUE TITLE
[Feature] Linked notes

### ISSUE THREAD

**Issue by ElectronicTeaCup** [taniarascia/takenote#267]
**Problem**
An interesting feature to connect one note to another could be via clickable links eg. [[my-other-note]].

**Solution**
Clickable links to reference and open other notes—maybe in another tab?

**Notes**
I saw this project from a Zettelkasten forum—it's basically a method of note taking which involves taking notes and connecting them to see emerging structure of the notes taken. This would be a great app for such users (myself included) since they want to aggregate their knowledge base over a long period of time.

**Comment by Mxchaeltrxn** [comment]
This is a feature that I've heard of and think is cool. I'll have to look into exactly how it works. 

@taniarascia Could I take this one on?

**Comment by taniarascia** [comment]
Sure thing! It'll be an interesting challenge to figure out how to consider a note unique. It's also something I'll have to consider if, when synced with GitHub, it uses filenames or uuids for each node.

**Comment by Mxchaeltrxn** [comment]
@taniarascia @ElectronicTeaCup  
I don't fully understand how considering a note to be unique fits into this picture. Could you explain this? 

After looking at the code and looking at this issue again, I'm not sure how to approach it given how this app runs.

The solution that I see works like this. Currently, to change the note we're viewing, we change the active note. I'm thinking we have a different route for each note so we can leverage markdown's regular link syntax to open the note in a new tab for a user. The problem here is I don't know what to do with files that have the same name that are in the same category in the sense that I don't know how the user chooses which note they want to select (I personally never really why someone would have a two files with the exact same name). 

I'm also not sure about how the Github sync works but you can't have duplicate filenames/directories in Github, right? 

If it were to work in edit mode, I'm not sure how to implement it.

Thoughts?

**Comment by taniarascia** [comment]
You asked how considering a note unique fits into the picture, but you answer the question here:

> The problem here is I don't know what to do with files that have the same name that are in the same category in the sense that I don't know how the user chooses which note they want to select

In Vim Wiki, you press double enter on a word or sentence, then it creates a new note with that file name and creates a link to that note. In this way, a note's filename is guaranteed unique. Any future attempt to link to that string will go to the already existing note. The file name is the uniqueness. With TakeNote, the unique part is the uuid, and the "title" is just some filtering of whatever is in the beginning of the note, so you can make a thousand notes with the same title. I didn't want to force the user to make a title/filename before typing because that's something that would be annoying for me personally.

I think it would involve quite a bit of refactor to change TakeNote to use routes instead of being a one-route, single page application.

**Comment by Mxchaeltrxn** [comment]
I've thought about it a little over the past few days but could not think of a good implementation. I also had some trouble installing vim wiki. I'm going to work on another issue first and then come back to this one. If someone else wants to take it in the meantime, feel free to.

It would also be okay to not use routes and instead of opening takenote in a new tab with the clicked note as active, we could just make the selected note active in the same window. I prefer this behaviour actually.

**Comment by taniarascia** [comment]
That's the behavior I would expect, as well. I imagine a Notion-esque functionality where you can highlight a sentence, and maybe right-click and link it to an existing note. Then double-clicking on the link would take you to it by making it the new active note.

**Comment by Mxchaeltrxn** [comment]
That implementation makes sense but I have some questions:

What confuses me is how to indicate to the user that the text is a link (and therefore is clickable). The way that I see is to automatically wrap the selected/highlighted text like so: <button onClick={directToNoteFunc} style={{color: 'blue', textDecoration: 'underline'}}>{selected text}</button>. This makes the editor text ugly but I don't see any alternatives. This allows the user to teleport to another note in the preview mode only. I'm also unsure if we want this feature in preview and/or editor mode.

**Comment by taniarascia** [comment]
I guess it makes a little more sense to me in preview mode. And it would be a _lot_ easier to develop. Everything else makes sense. The specific style for how to indicate a link doesn't matter too much, we can figure something out.

**Comment by kodyclemens** [comment]
I am going to work on this feature. Below is my understanding & what I am going to work to implement.

- Notes can be hyperlinked to one another within a note body
- A clickable link will be displayed in preview mode. Edit mode will just be markup, no links.
- Clicking a link in preview mode will load the appropriate target note, replacing the currently displayed note
- UUID will annotate a note's uniqueness (as opposed to title)
  - I think implementing this like GitHub does with commits and issues would be cool
    - Example: `#a4e4g5` will display a hyperlink as the target note's title in preview mode -> [Refactoring Apps](#)
    - In this PR or possibly in a future PR... after typing `#` in a note's body a list of notes will appear for selection:
      <img src="https://i.imgur.com/p1FnQdk.png" alt="example" width="250">
