### ISSUE TITLE
[Feature] Use tailwind.css for styling

### ISSUE THREAD

**Issue by Jfelix61** [taniarascia/takenote#312]
**Motivation**
With [tailwind.css](https://tailwindcss.com/) we can bootstrap new styled features faster. Also it can maintain a system that is more scalable in terms of styling. 

**Solution**
Integrating tailwind to the current codebase is pretty easy since it is just importing it to [index.scss](https://github.com/taniarascia/takenote/blob/master/src/client/styles/index.scss).

**Notes**
 Bundle size will not increase since Purge CSS will remove any unused CSS rule.

**Comment by taniarascia** [comment]
Hi @Jfelix61,

What advantage do you think this would bring to the TakeNote project? Since we're not using any library, there is no CSS code that is not used, and all of it is specifically tailored for the project. Furthermore, the classnames are semantic as opposed to utility classes, so each element only has a class that applies to what it actually is, vs. descriptors like `bg-white` and `border-1`, etc., which would lead to many classes on each element. Finally, all the end-to-end tests rely on the classes we've already created, so would have to be rewritten with new ways to account for this.

**Comment by Jfelix61** [comment]
End-to-end tests do create a problem. Having classes or selectors for tests can lead to breaks on the long-term since these could change. So, I ponder if we could add test ids which lead to a cleaner solution which gives contexts to tests. 

Regarding other styles, I believe using tailwind.css can lead us to have a more consistent design and since classes are reused bundle size would go down.

**Comment by taniarascia** [comment]
Tailwind seems like an interesting project, but it would be a lot of work to move to this component class-based approach and I haven't quite seen the benefits of it yet. It might be interesting to set up a project from scratch with Tailwind, but I don't think it will be on the road map for the current project.
