### ISSUE TITLE
[Dark mode] Toggling dark mode after putting notes in the trash brings the notes back from the trash

### ISSUE THREAD

**Issue by alphonseb** [taniarascia/takenote#47]

**Comment by Dantaro** [comment]
This appears to be due to Dark Mode reusing whatever is in Local Storage when it flips.

Steps to reproduce bug:
1) Create a new note
2) Save
3) Trash Note
4) Flip to Dark Mode
5) Note that the note is untrashed

Steps to reproduce actual issue
1) Create a new note
2) Trash Note
3) Save
4) Flip to Dark Mode
5) Note that the note is still trashed

I'll take a look at this later tonight unless someone beats me to it
