### ISSUE TITLE
Dark mode deactivates on page reload

### ISSUE THREAD

**Issue by dillionmegida** [taniarascia/takenote#76]
After activating dark mode, I discovered that on every page reload, it is deactivated.

There should be settings to save the current theme on the browser's storage system.

Thank you : )

**Comment by Dantaro** [comment]
@taniarascia Assign this to me

**Comment by taniarascia** [comment]
Add settings to local storage on sync for @Dantaro.

**Comment by Publicker** [comment]
@Dantaro Hey, what's up? 
How are you doing with this? If you need some help or anything, please feel free to do it 🤘

**Comment by Dantaro** [comment]
@Publicker If you want to grab it go for it, every time I've sat down to take a look at this I get about 5 minutes in before something comes up that pulls me away.  I was hoping to get to it this past weekend but obviously that never happened!  So sorry for the delay on this, life has just been hectic @taniarascia @MartinRosenberg .  I'm going to unassign myself but if I can find time soon I'll take a look but if others can take care of it now I don't want to hold up the process.

**Comment by taniarascia** [comment]
Note: The actual requirement for this ticket is that all settings should be saved to local storage, not just dark mode.

**Comment by deadpool1999** [comment]
hello,
my intro - a newbie to opensource, loves js, did a todo app with vanilla Js, nodeJs, mongodb,html,css.
no framework or template used, i like to work without a framework. I am thinking to work on a notes app, found this interesting repo, would love to hence work on this rather than creating one from scratch. I think, the preset code must be changed, to parse the preset from the localstorage (think that would help) {but am unable to find where that code is} .

**Comment by ashinzekene** [comment]
I'm working on this already
